version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./scripts:/app/scripts
      - ./workflows:/app/workflows
      - ./project_files:/app/project_files
      - ./index.html:/app/index.html
      - comfyui_output:/app/comfyui_output
    command: uvicorn scripts.main:app --host 0.0.0.0 --port 8000
    environment:
      - COMFYUI_URL=http://host.docker.internal:8188
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama

volumes:
  comfyui_output:
